name: ci

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/ci.yml"


jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    # need to watch vtk + mayavi wheels to be sure python version is supported

    - run: pip install -e .[tests]
    - run: flake8
    - run: mypy .
